openapi: 3.0.3
info:
  title: "API Proyecto Ecommerce"
  description: "Documentación inicial de la API en PHP Vanilla"
  version: "1.0.0"

servers:
  - url: "http://localhost:8080/api"
    description: "Servidor local de desarrollo"

paths: 
  /productos:
    get:
      tags:
        - Productos
      summary: Listar productos
      description: >
        Lista todos los productos con opciones avanzadas: <br><br>
        - paginación (`page`, `limit`) <br><br>
        - incluir categoría (`include=categoria`) <br><br>
        - ordenar por precio (`order=precio_asc|precio_desc`) <br><br>
        - búsqueda por nombre (`search=valor`) <br><br>
        - contar productos (`count=1`) <br><br>
        - filtrar por categoría (`id_categoria=5`)
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          description: Página actual para la paginación.
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
          description: Número de resultados por página.
        - in: query
          name: include
          schema:
            type: string
            enum: [categoria]
          description: Incluir información extendida de categoría.
        - in: query
          name: search
          schema:
            type: string
          description: Buscar productos por nombre.
        - in: query
          name: order
          schema:
            type: string
            enum: [precio_asc, precio_desc]
          description: Ordenar por precio ascendente o descendente.
        - in: query
          name: count
          schema:
            type: integer
            enum: [1]
          description: Devuelve solo el total de productos.
        - in: query
          name: id_categoria
          schema:
            type: integer
          description: Filtrar productos pertenecientes a una categoría específica.
      responses:
        "200":
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Producto"
        "400":
          description: Parámetros inválidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      tags:
        - Productos
      summary: Crear un nuevo producto
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_categoria:
                  type: integer
                nombre:
                  type: string
                descripcion:
                  type: string
                stock:
                  type: integer
                precio:
                  type: number
              required:
                - id_categoria
                - nombre
                - precio
      responses:
        "201":
          description: Producto creado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
        "400":
          description: Datos inválidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Token faltante o inválido
        "403":
          description: El usuario no tiene permisos
        "500":
          description: Error interno

  /productos/{id}:
    get:
      tags:
        - Productos
      summary: Obtener un producto por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del producto
        - in: query
          name: include
          schema:
            type: string
            enum: [categoria]
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Producto"
        "400":
          description: ID inválido
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Producto no encontrado

    put:
      tags:
        - Productos
      summary: Actualizar un producto
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_categoria:
                  type: integer
                nombre:
                  type: string
                descripcion:
                  type: string
                stock:
                  type: integer
                precio:
                  type: number
              required:
                - id_categoria
                - nombre
                - precio
      responses:
        "200":
          description: Producto actualizado correctamente
        "400":
          description: Parámetros inválidos
        "404":
          description: Producto no encontrado
        "401":
          description: Token inválido
        "403":
          description: Solo administradores
        "500":
          description: Error interno

    delete:
      tags:
        - Productos
      summary: Eliminar un producto
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Producto eliminado correctamente
        "400":
          description: ID inválido
        "404":
          description: Producto no encontrado
        "401":
          description: Token inválido
        "403":
          description: Solo administradores

  /login:
    post:
      tags:
        - Autenticación
      summary: Inicia sesión y obtiene un token JWT
      description: >
        Recibe correo y contraseña, valida las credenciales y devuelve un token JWT
        con id, correo, rol, fecha de emisión (iat) y expiración (exp).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - correo
                - password
              properties:
                correo:
                  type: string
                  example: admin@techstore.com
                password:
                  type: string
                  example: "admin123"
      responses:
        "200":
          description: Usuario autenticado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Token JWT para futuras peticiones
                    example: >
                      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        "400":
          description: Faltan datos obligatorios
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "correo y contraseña son obligatorios"
        "404":
          description: Usuario no encontrado o credenciales incorrectas
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "usuario no encontrado"
        "405":
          description: Método no permitido
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Método no permitido. Usa POST."
  /me:
    get:
      tags:
        - Autenticación
      summary: Obtiene la información del usuario autenticado
      description: >
        Devuelve los datos del usuario basados en el token JWT enviado en la cabecera
        Authorization: Bearer <token>.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Datos del usuario autenticado
          content:
            application/json:
              schema:
                type: object
                properties:
                  nombre:
                    type: string
                    example: "Juan Pérez"
                  correo:
                    type: string
                    example: "juan@example.com"
                  rol:
                    type: string
                    example: "admin"
        "401":
          description: Token ausente o inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Token inválido o expirado"
        "404":
          description: Usuario no encontrado en la base de datos
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /version:
    get:
      tags:
        - Utilidades
      summary: Muestra la versión de la API
      description: Devuelve la versión actual de la API y una breve descripción.
      responses:
        "200":
          description: Información de la versión de la API
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: "1.0.0"
                  descripcion:
                    type: string
                    example: "API del e-commerce TechUniverse"


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        nombre:
          type: string
        rol:
          type: string
      required:
        - id
        - email

    Producto:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        precio:
          type: number
        categoria_id:
          type: integer

    Categoria:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string

    Error:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string